#!/usr/bin/env perl

use strict;
use warnings;

use IO::All qw/io/;

my $MAX_ITERS = 10000;

my $THEME = q#--method random-dfs -to '[01][2345]' -sp r:tf -opt -opt-to '0123456789ABCDE'#;

my $OUTPUT_PATH = "$ENV{HOME}/Backup/Arcs/fcs-summary-len-seed";

my $BASE = 'theme1';

io->dir($OUTPUT_PATH)->mkpath;

foreach my $seed (1 .. 1000)
{
    my $out_fn = qq#$OUTPUT_PATH/lens-$BASE--seed=$seed.txt#;
    if (! -e $out_fn)
    {
        my $cmd = qq#./summary-fc-solve \$(seq 1 32000) -- $THEME -seed $seed -mi $MAX_ITERS | tee -a "$out_fn" | grep Unsolved#;
        print "$cmd\n";
        system($cmd);
    }
}

__END__

=head1 COPYRIGHT AND LICENSE

This file is part of Freecell Solver. It is subject to the license terms in
the COPYING.txt file found in the top-level directory of this distribution
and at http://fc-solve.shlomifish.org/docs/distro/COPYING.html . No part of
Freecell Solver, including this file, may be copied, modified, propagated,
or distributed except according to the terms contained in the COPYING file.

Copyright (c) 2016 Shlomi Fish

=cut
