DOC = fcs_arch_doc

UPLOAD_PATH = shlomif@shell.berlios.de:/home/groups/fc-solve/htdocs/arch_doc/

MORE_XML_FILES = code_overview.xml coding_conventions.xml techniques.xml scm.xml terms.xml

include docmake.mak

