#!/bin/bash
for (( deal_idx=1 ; deal_idx<=32000 ; ++deal_idx ))
do
    printf "%-6s| %-30s | %-30s | %-30s\n" \
        "$deal_idx" \
        "$(pi-make-microsoft-freecell-board -t "$deal_idx" | ./scripts/summarize-fc-solve --read-from-file 4,'/home/shlomif/progs/freecell/git/fc-solve/fc-solve/source/Presets/testing-presets/flares-with-non-parents-1.sh')" \
        "$(pi-make-microsoft-freecell-board -t "$deal_idx" | ./scripts/summarize-fc-solve --read-from-file 4,'/home/shlomif/progs/freecell/git/fc-solve/fc-solve/source/Presets/testing-presets/flares-with-non-parents-2.sh')" \
        "$(pi-make-microsoft-freecell-board -t "$deal_idx" | ./scripts/summarize-fc-solve --read-from-file 4,'/home/shlomif/progs/freecell/git/fc-solve/fc-solve/source/Presets/testing-presets/flares-with-non-parents-3.sh')"
done
