#!/bin/bash
for I in `seq 1 32000` ; do
# for I in `seq 8389 32000` ; do
    printf "%-6s| %-30s | %-30s | %-30s\n" \
        "$I" \
        "$(pi-make-microsoft-freecell-board -t "$I" | ./scripts/summarize-fc-solve --read-from-file 4,'/home/shlomif/progs/freecell/git/fc-solve/fc-solve/source/Presets/testing-presets/flares-with-non-parents-1.sh')" \
        "$(pi-make-microsoft-freecell-board -t "$I" | ./scripts/summarize-fc-solve --read-from-file 4,'/home/shlomif/progs/freecell/git/fc-solve/fc-solve/source/Presets/testing-presets/flares-with-non-parents-2.sh')" \
        "$(pi-make-microsoft-freecell-board -t "$I" | ./scripts/summarize-fc-solve --read-from-file 4,'/home/shlomif/progs/freecell/git/fc-solve/fc-solve/source/Presets/testing-presets/flares-with-non-parents-3.sh')"
done
