=head1 NAME

freecell-solver-config - DEPRECATED - use pkg-config with libfreecell-solver instead

=head1 USAGE

Usage: freecell-solver-config [OPTIONS]
Options:
    [--prefix=[DIR]]
    [--exec-prefix=[DIR]]
    [--version]
    [--libs]
    [--cflags]

=head1 DESCRIPTION

This program allows one to build using libfreecell-solver and dependencies.
One should no longer use it and use pkg-config instead.

=head1 SEE ALSO

B<pkg-config> (1)

=head1 AUTHOR

Shlomi Fish, L<http://www.shlomifish.org/> .

=cut
