/*
    test_num.h - this file contains constants of the number of tests
    and their aliases mapping. It is auto-generated by gen_tests_list.pl
    and should not be edited by hand.

    This file is under the public domain.
*/
#define FCS_TESTS_NUM 24

#define FCS_TESTS_ALIASES_NUM 24
