/*
    tests.c - this file contains the definition of the test functions
    and their aliases mapping. It is auto-generated by gen_tests_list.pl
    and should not be edited by hand.
    
    This file is under the public domain.
*/

#include "tests.h"

freecell_solver_solve_for_state_test_t freecell_solver_sfs_tests[FCS_TESTS_NUM] =
{
    freecell_solver_sfs_move_top_stack_cards_to_founds,
    freecell_solver_sfs_move_freecell_cards_to_founds,
    freecell_solver_sfs_move_freecell_cards_on_top_of_stacks,
    freecell_solver_sfs_move_non_top_stack_cards_to_founds,
    freecell_solver_sfs_move_stack_cards_to_different_stacks,
    freecell_solver_sfs_move_stack_cards_to_a_parent_on_the_same_stack,
    freecell_solver_sfs_move_sequences_to_free_stacks,
    freecell_solver_sfs_move_freecell_cards_to_empty_stack,
    freecell_solver_sfs_move_cards_to_a_different_parent,
    freecell_solver_sfs_empty_stack_into_freecells,
    freecell_solver_sfs_atomic_move_card_to_empty_stack,
    freecell_solver_sfs_atomic_move_card_to_parent,
    freecell_solver_sfs_atomic_move_card_to_freecell,
    freecell_solver_sfs_atomic_move_freecell_card_to_parent,
    freecell_solver_sfs_atomic_move_freecell_card_to_empty_stack,
    freecell_solver_sfs_simple_simon_move_sequence_to_founds,
    freecell_solver_sfs_simple_simon_move_sequence_to_true_parent,
    freecell_solver_sfs_simple_simon_move_whole_stack_sequence_to_false_parent,
    freecell_solver_sfs_simple_simon_move_sequence_to_true_parent_with_some_cards_above,
    freecell_solver_sfs_simple_simon_move_sequence_with_some_cards_above_to_true_parent,
    freecell_solver_sfs_simple_simon_move_sequence_with_junk_seq_above_to_true_parent_with_some_cards_above,
    freecell_solver_sfs_simple_simon_move_whole_stack_sequence_to_false_parent_with_some_cards_above,
    freecell_solver_sfs_simple_simon_move_sequence_to_parent_on_the_same_stack,
    freecell_solver_sfs_simple_simon_move_sequence_to_false_parent
};

fcs_test_aliases_mapping_t freecell_solver_sfs_tests_aliases[FCS_TESTS_ALIASES_NUM] =
{
    { "0", 0 },
    { "1", 1 },
    { "2", 2 },
    { "3", 3 },
    { "4", 4 },
    { "5", 5 },
    { "6", 6 },
    { "7", 7 },
    { "8", 8 },
    { "9", 9 },
    { "A", 10 },
    { "B", 11 },
    { "C", 12 },
    { "D", 13 },
    { "E", 14 },
    { "a", 15 },
    { "b", 16 },
    { "c", 17 },
    { "d", 18 },
    { "e", 19 },
    { "f", 20 },
    { "g", 21 },
    { "h", 22 },
    { "i", 23 }
};
