#!/bin/bash

# This script aims to be a template for further scripts for summarizing a
# range of deals in a table.

for (( deal=1 ; deal<=8 ; ++deal ))
do
    # printf "%-6s| %-25s | %-30s\n" \
    printf "%s\t%s\t%s\n" \
        "$deal" \
        "$(pi-make-microsoft-freecell-board -t "$deal" | summarize-fc-solve)" \
        "$(pi-make-microsoft-freecell-board -t "$deal" | summarize-fc-solve --method a-star)"
done
