package rejects::MyNavData;

use strict;
use warnings;

=begin Removed

                {
                    'text' => "PySol Integration",
                    'url' => "pysol/",
                },

                {
                    'text' => "Doxygen",
                    'title' => ("Hypertext documentation for the Freecell " .
                        "Solver code generated by Doxygen"),
                    'url' => "http://fc-solve.shlomifish.org/michael_mann/",
                    'url_is_abs' => 1,
                    'skip' => 1,
                },

        {
            'text' => "Status",
            'url' => "current-status.html",
            'title' => "What is the current status of Freecell Solver? Is it dead?",
        },

        {
            'text' => "The Book",
            'url' => "book.html",
        },

=end Removed

=cut

1;
