#! /usr/bin/env python3
#
# Copyright © 2018 Shlomi Fish <shlomif@cpan.org>
#
# Distributed under terms of the MIT license.

import sys


from pysol_cards.gen_multi_cli import GenMultiParseCmdLine


def _cli_main():
    sys.exit(GenMultiParseCmdLine(argv=sys.argv).run())


if __name__ == "__main__":
    _cli_main()
