#!/bin/bash

script_dirname="$(dirname $BASH_SOURCE[-1])"
source "$script_dirname/fc_solve_common.bash"

cd "$FCS_PATH" && perl "$FCS_SRC_PATH"/../scripts/parallel-solve-from-source-distro/parallel-range-solver-total --mode solve
