#!/usr/bin/perl

use strict;
use warnings;

use Games::Solitaire::Verify::App::CmdLine::From_ShirlHartSolver ();

my $app = Games::Solitaire::Verify::App::CmdLine::From_ShirlHartSolver->new(
    { argv => \@ARGV } );

$app->run();

=head1 NAME

convert-shirl-hart-solver-to-fc-solve-solution -- A command-line tool for converting
Shirl Hart's freecell solver solutions to Freecell Solver's.

=head1 SYNOPSIS

    $ convert-patsolve-to-fc-solve-solution -g freecell 24.board ./24.shirl-hart.sol > 24.sol
    $ verify-solitaire-solution -g freecell ./24.sol

=head1 COMMAND LINE OPTIONS

=head2 -g [variant]

Picks up a variant.

=head2 --decks-num [1|2]

Number of decks - 1 or 2.

=head2 --freecells-num [n]

Number of freecells.

=head2 --stacks-num [n]

Number of columns.

=head2 --sequences-are-built-by [alternate_color|alt_color|suit|rank]

How the sequences are built by.

=head2 --empty-stacks-filled-by [any|kings|none]

What empty stacks can be filled by.

=head2 --sequence-move [limited|unlimited]

Whether the sequence move is limited or unlimited.

=head1 AUTHORS

Shlomi Fish, L<https://www.shlomifish.org/> .

=head1 COPYRIGHT & LICENSE

Copyright 2010 Shlomi Fish.

This program is released under the following license: MIT/Expat
( L<http://www.opensource.org/licenses/mit-license.php> ).

=cut
